kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql-slave1
  labels:
    name: mysql-slave1
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql-slave1
  serviceName: mysql-slave1
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-slave1
    spec:
      containers:
      - name: mysql-slave1
        image: alanpeng/mysql5.7-replication-docker
        ports:
        - containerPort: 3306
        env:
        - name: MySQL_Role
          value: "Slave1"
        - name: MYSQL_ROOT_PASSWORD
          value: "password"    
        - name: REPLICATION_USER
          value: "repluser"          
        - name: REPLICATION_PASSWORD
          value: "88888888"         
        - name: MasterIP
          value: "mysql-master"         
        - name: Slave1IP
          value: "mysql-slave1"         
        - name: Slave2IP
          value: "mysql-slave2"            
        - name: MySQLPort
          value: "3306"          
        volumeMounts:
          - name: mysql-slave1-v
            mountPath: /var/lib/mysql
      nodeSelector:
        nodetype: mysql-slave1
      volumes:
        - name: mysql-slave1-v
          persistentVolumeClaim:
            claimName: mysql-slave1-pvc
